# Generated by Django 5.2.7 on 2025-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('alcance', models.FloatField(blank=True, null=True)),
                ('guardia', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('golpes_por_minuto', models.FloatField(blank=True, null=True)),
                ('precision_golpes', models.FloatField(blank=True, null=True)),
                ('golpes_recibidos', models.FloatField(blank=True, null=True)),
                ('defensa_golpes', models.FloatField(blank=True, null=True)),
                ('derribos_promedio', models.FloatField(blank=True, null=True)),
                ('precision_derribos', models.FloatField(blank=True, null=True)),
                ('defensa_derribos', models.FloatField(blank=True, null=True)),
                ('sumisiones_promedio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
