# Generated by Django 5.2.7 on 2025-10-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peleadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peleador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='peleadores/'),
        ),
    ]
